/**
 * OutputPreview — Renders the generated UI output.
 * Supports two views: visual Preview and Code view.
 * Uses DOMPurify for safe HTML rendering.
 */
import React, { useState, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Eye, Code, Copy, Check, Download, RefreshCw, Lightbulb, Share2, ExternalLink, FileText, ShieldAlert, ShieldCheck, Sliders, ArrowLeftRight } from 'lucide-react';
import JSZip from 'jszip';
import useGeneratorStore from '../../store/generatorStore';
import { sanitizeHTML } from '../../utils/security';
import Button from '../ui/Button';
import MatrixControls from './MatrixControls';
import './OutputPreview.css';

export default function OutputPreview() {
  const {
    currentOutput, outputView, setOutputView,
    explainMode, toggleExplainMode, retry, error,
    generationPhase, addToCompare, compareMode, compareItems,
    setRefineMode, currentAudit, quantumFix
  } = useGeneratorStore();
  
  const [showMatrix, setShowMatrix] = useState(false);
  const [copied, setCopied] = useState(false);
  const [shared, setShared] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  const [matrixValues, setMatrixValues] = useState({
    blur: 40,
    saturate: 220,
    padding: 2,
    gap: 1.5
  });

  const handleMatrixChange = (key, val) => {
    setMatrixValues(prev => ({ ...prev, [key]: val }));
  };

  const [activeScreenIndex, setActiveScreenIndex] = useState(0);

  const activeOutput = useMemo(() => {
    if (currentOutput?.isFlow) return currentOutput.screens[activeScreenIndex];
    return currentOutput;
  }, [currentOutput, activeScreenIndex]);

  const safeHTML = useMemo(() => {
    if (!activeOutput?.html) return '';
    return sanitizeHTML(activeOutput.html);
  }, [activeOutput?.html]);

  const codeToShow = useMemo(() => {
    if (!activeOutput) return '';
    
    // Inject current Matrix values into the CSS for the code view
    const morphedCss = activeOutput.css
      .replace(/--m-blur:\s*[^;]+;/, `--m-blur: ${matrixValues.blur}px;`)
      .replace(/--m-saturate:\s*[^;]+;/, `--m-saturate: ${matrixValues.saturate}%;`)
      .replace(/--m-padding:\s*[^;]+;/, `--m-padding: ${matrixValues.padding}rem;`)
      .replace(/--m-gap:\s*[^;]+;/, `--m-gap: ${matrixValues.gap}rem;`);

    if (outputView === 'code') return activeOutput.jsx;
    if (outputView === 'docs') return `
# ${currentOutput.componentType} Component (Customized)

This component has been curated using the Design Matrix.

## Applied Curation
- **Luminance (Blur)**: ${matrixValues.blur}px
- **Energy (Saturate)**: ${matrixValues.saturate}%
- **Gravity (Padding)**: ${matrixValues.padding}rem

## Usage
\`\`\`jsx
/* Copy the CSS from the other tab and use this component */
import { ${currentOutput.componentType} } from './components';

export default function App() {
  return <${currentOutput.componentType} />;
}
\`\`\`
    `;
    return morphedCss;
  }, [currentOutput, outputView, matrixValues]);

  const handleCopy = async (text) => {
    try {
      await navigator.clipboard.writeText(text || currentOutput?.jsx || '');
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for non-HTTPS
      const area = document.createElement('textarea');
      area.value = text || currentOutput?.jsx || '';
      document.body.appendChild(area);
      area.select();
      document.execCommand('copy');
      document.body.removeChild(area);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownload = async () => {
    if (!currentOutput) return;
    setIsDownloading(true);
    try {
      const zip = new JSZip();
      const folderName = `${currentOutput.componentType || 'component'}-${currentOutput.style || 'modern'}`;
      const folder = zip.folder(folderName);
      
      folder.file('Component.jsx', currentOutput.jsx);
      folder.file('Component.css', currentOutput.css);
      folder.file('Preview.html', currentOutput.html);
      folder.file('README.md', `# ${folderName}\n\nGenerated by UI Intelligence Engine.\n\n## Usage\n1. Copy the JSX and CSS into your project.\n2. Ensure you have Lucide Icons installed if applicable.`);
      
      const content = await zip.generateAsync({ type: 'blob' });
      const link = document.createElement('a');
      link.href = URL.createObjectURL(content);
      link.download = `${folderName}.zip`;
      link.click();
    } catch (err) {
      console.error('Download failed:', err);
    } finally {
      setIsDownloading(false);
    }
  };

  const handleShare = () => {
    // Simulated public URL sharing
    const shareUrl = `${window.location.origin}/preview/${currentOutput.id}`;
    navigator.clipboard.writeText(shareUrl).then(() => {
      setShared(true);
      setTimeout(() => setShared(false), 2000);
    });
  };

  const handleStackBlitz = () => {
    if (!currentOutput) return;
    const project = {
      files: {
        'index.js': `import React from 'react';\nimport ReactDOM from 'react-dom';\nimport './style.css';\nimport { App } from './App';\n\nReactDOM.render(<App />, document.getElementById('root'));`,
        'App.js': currentOutput.jsx,
        'style.css': currentOutput.css,
        'index.html': `<div id="root"></div>`,
        'package.json': JSON.stringify({
          name: 'generated-ui',
          dependencies: { 
            'react': '^18.2.0', 
            'react-dom': '^18.2.0',
            'lucide-react': 'latest',
            'framer-motion': 'latest'
          }
        }, null, 2)
      },
      title: `Generated ${currentOutput.componentType}`,
      description: 'Built with UI Intelligence Engine',
      template: 'javascript'
    };

    const form = document.createElement('form');
    form.method = 'POST';
    form.action = 'https://stackblitz.com/run';
    form.target = '_blank';

    Object.entries(project.files).forEach(([path, content]) => {
      const input = document.createElement('input');
      input.type = 'hidden';
      input.name = `project[files][${path}]`;
      input.value = content;
      form.appendChild(input);
    });

    const titleInput = document.createElement('input');
    titleInput.type = 'hidden';
    titleInput.name = 'project[title]';
    titleInput.value = project.title;
    form.appendChild(titleInput);

    document.body.appendChild(form);
    form.submit();
    document.body.removeChild(form);
  };

  // Error state
  if (generationPhase === 'error') {
    return (
      <motion.div
        className="output-error"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
      >
        <div className="output-error__icon">⚠️</div>
        <h3 className="output-error__title">Generation Failed</h3>
        <p className="output-error__message">{error}</p>
        <Button variant="outline" icon={RefreshCw} onClick={retry}>
          Retry
        </Button>
      </motion.div>
    );
  }

  if (!currentOutput) return null;

  return (
    <motion.div
      className="output-preview glass-card"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
    >
      {/* Flow Mode Carousel (Master Upgrade) */}
      {currentOutput?.isFlow && (
        <div className="output-preview__flow-nav">
          {currentOutput.screens.map((screen, idx) => (
            <button
              key={screen.id}
              className={`output-preview__flow-btn ${activeScreenIndex === idx ? 'active' : ''}`}
              onClick={() => setActiveScreenIndex(idx)}
            >
              <span className="flow-step">{idx + 1}</span>
              <span className="flow-label">{screen.componentType}</span>
            </button>
          ))}
        </div>
      )}

      {/* Toolbar */}
      <div className="output-preview__toolbar">
        <div className="output-preview__tabs">
          <button
            className={`output-preview__tab ${outputView === 'preview' ? 'output-preview__tab--active' : ''}`}
            onClick={() => setOutputView('preview')}
          >
            <Eye size={14} /> Preview
          </button>
          <button
            className={`output-preview__tab ${outputView === 'code' ? 'output-preview__tab--active' : ''}`}
            onClick={() => setOutputView('code')}
          >
            <Code size={14} /> JSX
          </button>
          <button
            className={`output-preview__tab ${outputView === 'docs' ? 'output-preview__tab--active' : ''}`}
            onClick={() => setOutputView('docs')}
          >
            <FileText size={14} /> Docs
          </button>
        </div>

        <div className="output-preview__actions">
          <button
            className={`output-preview__action-btn ${explainMode ? 'output-preview__action-btn--active' : ''}`}
            onClick={toggleExplainMode}
            title="Explain design decisions"
          >
            <Lightbulb size={14} />
          </button>

          {/* God-Tier Quantum Fix Button */}
          {currentAudit?.score < 95 && (
            <motion.button
              className="output-preview__quantum-btn"
              onClick={quantumFix}
              title={`Auto-Fix ${currentAudit.findings.length} Audit Findings`}
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
            >
              <ShieldAlert size={14} />
              <span>Quantum Fix</span>
            </motion.button>
          )}
          
          {/* Comparison Action */}
          <Button
            variant={compareItems.find(i => i.id === currentOutput.id) ? "primary" : "ghost"}
            size="sm"
            onClick={() => addToCompare(currentOutput)}
            disabled={compareItems.length >= 2 && !compareItems.find(i => i.id === currentOutput.id)}
            title={compareItems.length >= 2 ? "Comparison queue full" : "Add to comparison pool"}
          >
            <ArrowLeftRight size={14} />
            <span>{compareItems.find(i => i.id === currentOutput.id) ? 'Queued' : 'Compare'}</span>
          </Button>

          <Button
            variant="ghost"
            size="sm"
            icon={RefreshCw}
            onClick={() => setRefineMode(currentOutput.id)}
          >
            Refine
          </Button>
          
          <button
            className="output-preview__action-btn"
            onClick={handleStackBlitz}
            title="Open in StackBlitz"
          >
            <ExternalLink size={14} />
          </button>
          
          <button
            className="output-preview__action-btn"
            onClick={handleDownload}
            disabled={isDownloading}
            title="Download ZIP"
          >
            <Download size={14} className={isDownloading ? 'animate-spin' : ''} />
          </button>

          <button
            className={`output-preview__action-btn ${shared ? 'output-preview__action-btn--active' : ''}`}
            onClick={handleShare}
            title="Share preview link"
          >
            {shared ? <Check size={14} /> : <Share2 size={14} />}
          </button>

          <button
            className={`output-preview__action-btn ${showMatrix ? 'output-preview__action-btn--active' : ''}`}
            onClick={() => setShowMatrix(!showMatrix)}
            title="Toggle Design Matrix (Real-time curation)"
          >
            <Sliders size={14} />
          </button>

          <button
            className="output-preview__action-btn"
            onClick={() => handleCopy()}
            title="Copy code"
          >
            {copied ? <Check size={14} /> : <Copy size={14} />}
          </button>
        </div>
      </div>

      {/* Content */}
      <AnimatePresence mode="wait">
        {outputView === 'preview' ? (
          <motion.div
            key="preview"
            className="output-preview__canvas"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
          >
            <AnimatePresence>
              {showMatrix && (
                <MatrixControls 
                  values={matrixValues} 
                  onChange={handleMatrixChange} 
                  onClose={() => setShowMatrix(false)}
                />
              )}
            </AnimatePresence>
            
            <style>{activeOutput.css}</style>
            <div
              className="output-preview__render"
              style={{
                '--m-blur': `${matrixValues.blur}px`,
                '--m-saturate': `${matrixValues.saturate}%`,
                '--m-padding': `${matrixValues.padding}rem`,
                '--m-gap': `${matrixValues.gap}rem`,
              }}
              dangerouslySetInnerHTML={{ __html: safeHTML }}
            />
          </motion.div>
        ) : outputView === 'code' ? (
          <motion.div
            key="code"
            className="output-preview__code"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
          >
            <pre className="output-preview__pre">
              <code>{currentOutput.jsx}</code>
            </pre>
          </motion.div>
        ) : (
           <motion.div
            key="docs"
            className="output-preview__docs"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
          >
            <div className="output-preview__readme">
               <pre className="output-preview__pre">
                 <code>{codeToShow}</code>
               </pre>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Explain Mode Panel */}
      <AnimatePresence>
        {explainMode && currentOutput.explanation && (
          <motion.div
            className="output-preview__explain"
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.3 }}
          >
            <h4 className="output-preview__explain-title">
              <Lightbulb size={16} /> Design Rationale
            </h4>
            <div className="output-preview__explain-grid">
              {Object.entries(currentOutput.explanation).map(([key, value]) => (
                <div key={key} className="output-preview__explain-item">
                  <span className="output-preview__explain-label">{key}</span>
                  <p className="output-preview__explain-text">{value}</p>
                </div>
              ))}
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Meta info */}
      <div className="output-preview__meta">
        <span className="output-preview__meta-item">
          Type: <strong>{currentOutput.componentType}</strong>
        </span>
        <span className="output-preview__meta-item">
          Style: <strong>{currentOutput.style}</strong>
        </span>
        <span className="output-preview__meta-item">
          Confidence: <strong>{Math.round((currentOutput.analysis?.confidence || 0.5) * 100)}%</strong>
        </span>
      </div>
    </motion.div>
  );
}
