/**
 * PublicPreviewPage — A standalone, simplified view of a generated component.
 * Used for "Share Link" functionality.
 */
import React, { useEffect, useState, useMemo } from 'react';
import { useParams, Link } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { Sparkles, ArrowLeft, Terminal } from 'lucide-react';
import { sanitizeHTML } from '../utils/security';
import Button from '../components/ui/Button';
import useGeneratorStore from '../store/generatorStore';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:3001/api';

export default function PublicPreviewPage() {
  const { id } = useParams();
  const [component, setComponent] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchItem = async () => {
      try {
        const res = await fetch(`${API_URL}/history/public/${id}`);
        if (!res.ok) throw new Error('Preview not found');
        const data = await res.json();
        setComponent(data);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };
    fetchItem();
  }, [id]);

  const safeHTML = useMemo(() => {
    if (!component?.html) return '';
    return sanitizeHTML(component.html);
  }, [component?.html]);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen text-center p-6">
        <div className="page-loader__spinner mb-4" />
        <p className="text-muted-foreground">Loading preview...</p>
      </div>
    );
  }

  if (error || !component) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen text-center p-6">
        <h2 className="text-2xl font-bold mb-4">Preview Not Found</h2>
        <p className="text-muted-foreground mb-8">{error || 'This component may have been deleted or the link is incorrect.'}</p>
        <Link to="/">
          <Button variant="primary">Back to Home</Button>
        </Link>
      </div>
    );
  }

  return (
    <div className="public-preview min-h-screen flex flex-col">
      <header className="public-preview__header glass-card m-4 p-4 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Link to="/dashboard">
            <Button variant="ghost" size="sm" icon={ArrowLeft}>Dashboard</Button>
          </Link>
          <div>
            <h1 className="text-lg font-bold flex items-center gap-2">
              <Sparkles size={18} className="text-accent-400" />
              {component.componentType} Preview
            </h1>
            <p className="text-xs text-muted-foreground">Original Prompt: {component.prompt}</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Link to="/auth">
            <Button variant="primary" size="sm">Build Your Own</Button>
          </Link>
        </div>
      </header>

      <main className="flex-1 p-8 flex items-center justify-center overflow-auto">
        <motion.div 
          className="max-w-4xl w-full"
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
        >
          <style>{component.css}</style>
          <div
            className="output-preview__render shadow-2xl rounded-xl overflow-hidden"
            dangerouslySetInnerHTML={{ __html: safeHTML }}
          />
        </motion.div>
      </main>

      <footer className="p-4 text-center text-xs text-muted-foreground">
        Generated by <strong>UI Intelligence Engine</strong> — AI-Driven Design Systems
      </footer>
    </div>
  );
}
